"""Add shared-access and alias fields

Revision ID: c2db8294095d
Revises: 
Create Date: 2025-04-28 09:27:14.601768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2db8294095d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Remove any leftover temp tables from previous failed attempts
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_comment")
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_photo")
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_shared_access")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commenter_alias', sa.String(length=80), nullable=False))
        batch_op.drop_column('author_name')

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploader_alias', sa.String(length=80), nullable=False))

    with op.batch_alter_table('shared_access', schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('shared_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('alias', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('require_upload_approval', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('require_comment_approval', sa.Boolean(), nullable=True))
        # Remove old columns
        batch_op.drop_column('access_name')
        batch_op.drop_column('email')
        batch_op.drop_column('primary_user_id')
        # Create named foreign key constraints
        batch_op.create_foreign_key(
            'fk_shared_access_shared_user',
            'user', ['shared_user_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_shared_access_owner',
            'user', ['owner_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_access', schema=None) as batch_op:
        # Re-add old columns
        batch_op.add_column(sa.Column('primary_user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('access_name', sa.VARCHAR(length=80), nullable=False))
        # Create named foreign key for rollback
        batch_op.create_foreign_key(
            'fk_shared_access_primary_user',
            'user', ['primary_user_id'], ['id']
        )
        # Remove new columns
        batch_op.drop_column('require_comment_approval')
        batch_op.drop_column('require_upload_approval')
        batch_op.drop_column('alias')
        batch_op.drop_column('shared_user_id')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('uploader_alias')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('commenter_alias')
    # ### end Alembic commands ###
